// Generated by branding/gen_icons_kt.py from design/screens. Do not edit by hand.
package com.geekvpn.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

/** The design's 24dp stroke icons. Tint them with Icon(tint = ...); the black here is a mask. */
object GeekIcons {
    val User: ImageVector by lazy {
        icon("User") {
            stroke("M8 8a4 4 0 1 0 8 0a4 4 0 1 0 -8 0z")
            stroke("M4 21c1.5-4 4.5-6 8-6s6.5 2 8 6")
        }
    }

    val Telegram: ImageVector by lazy {
        icon("Telegram") {
            stroke("M21 4 3 11l7 2 2 7z")
            stroke("m10 13 5-4")
        }
    }

    val Wallet: ImageVector by lazy {
        icon("Wallet") {
            stroke("M6 6h12a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3z")
            stroke("M16 13h2")
            stroke("M6 6V5a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1")
        }
    }

    val Plus: ImageVector by lazy {
        icon("Plus") {
            stroke("M12 5v14M5 12h14")
        }
    }

    val Refresh: ImageVector by lazy {
        icon("Refresh") {
            stroke("M20 11a8 8 0 0 0-14.5-4.5L4 8")
            stroke("M4 3v5h5")
            stroke("M4 13a8 8 0 0 0 14.5 4.5L20 16")
            stroke("M20 21v-5h-5")
        }
    }

    val Globe: ImageVector by lazy {
        icon("Globe") {
            stroke("M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0z")
            stroke("M3 12h18")
            stroke("M12 3c2.5 2.7 3.8 5.7 3.8 9s-1.3 6.3-3.8 9c-2.5-2.7-3.8-5.7-3.8-9S9.5 5.7 12 3z")
        }
    }

    val ChevronStart: ImageVector by lazy {
        icon("ChevronStart") {
            stroke("m15 6-6 6 6 6")
        }
    }

    val Route: ImageVector by lazy {
        icon("Route") {
            stroke("M4 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
            stroke("M16 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
            stroke("M6 17V9a4 4 0 0 1 4-4h6")
            stroke("M6 13h8a4 4 0 0 1 4 4v2")
        }
    }

    val Sliders: ImageVector by lazy {
        icon("Sliders") {
            stroke("M4 7h10M18 7h2M4 17h4M12 17h8")
            stroke("M14 7a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
            stroke("M8 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
        }
    }

    val Folder: ImageVector by lazy {
        icon("Folder") {
            stroke("M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z")
        }
    }

    val ThemeAuto: ImageVector by lazy {
        icon("ThemeAuto") {
            stroke("M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0z")
            fill("M12 3a9 9 0 0 1 0 18z")
        }
    }

    val Sun: ImageVector by lazy {
        icon("Sun") {
            stroke("M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0z")
            stroke("M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4")
        }
    }

    val Moon: ImageVector by lazy {
        icon("Moon") {
            stroke("M20 14.5A8 8 0 0 1 9.5 4 8 8 0 1 0 20 14.5z")
        }
    }

    val Headset: ImageVector by lazy {
        icon("Headset") {
            stroke("M4 15v-3a8 8 0 0 1 16 0v3")
            stroke("M4.5 14h1a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1 -1.5 1.5h-1a1.5 1.5 0 0 1 -1.5 -1.5v-3a1.5 1.5 0 0 1 1.5 -1.5z")
            stroke("M18.5 14h1a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1 -1.5 1.5h-1a1.5 1.5 0 0 1 -1.5 -1.5v-3a1.5 1.5 0 0 1 1.5 -1.5z")
        }
    }

    val Download: ImageVector by lazy {
        icon("Download") {
            stroke("M12 4v11")
            stroke("m7 10 5 5 5-5")
            stroke("M5 20h14")
        }
    }

    val Logout: ImageVector by lazy {
        icon("Logout") {
            stroke("M14 4h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-4")
            stroke("M10 16l-4-4 4-4")
            stroke("M6 12h10")
        }
    }

    val Home: ImageVector by lazy {
        icon("Home") {
            stroke("M3 10.5 12 3l9 7.5")
            stroke("M5 9.5V20h14V9.5")
            stroke("M10 20v-6h4v6")
        }
    }

    val Shield: ImageVector by lazy {
        icon("Shield") {
            stroke("M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z")
            stroke("m9 12 2 2 4-4")
        }
    }

    val Bag: ImageVector by lazy {
        icon("Bag") {
            stroke("M6 8h12l-1 12H7z")
            stroke("M9 8V6a3 3 0 0 1 6 0v2")
        }
    }

    val Bank: ImageVector by lazy {
        icon("Bank") {
            stroke("M3 10 12 4l9 6")
            stroke("M5 10v8M9 10v8M15 10v8M19 10v8M3 20h18")
        }
    }

    val Copy: ImageVector by lazy {
        icon("Copy") {
            stroke("M11.5 9h6a2.5 2.5 0 0 1 2.5 2.5v6a2.5 2.5 0 0 1 -2.5 2.5h-6a2.5 2.5 0 0 1 -2.5 -2.5v-6a2.5 2.5 0 0 1 2.5 -2.5z")
            stroke("M5 15V6a2 2 0 0 1 2-2h8")
        }
    }

    val Clock: ImageVector by lazy {
        icon("Clock") {
            stroke("M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0z")
            stroke("M12 7v5l3 2")
        }
    }

    val Receipt: ImageVector by lazy {
        icon("Receipt") {
            stroke("M6 3h12v18l-3-2-3 2-3-2-3 2z")
            stroke("M9 8h6M9 12h6")
        }
    }

    val Unlink: ImageVector by lazy {
        icon("Unlink") {
            stroke("M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7")
            stroke("M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7")
            stroke("M4 4l16 16")
        }
    }

    val Check: ImageVector by lazy {
        icon("Check") {
            stroke("m5 12 5 5 9-10")
        }
    }

    val Link: ImageVector by lazy {
        icon("Link") {
            stroke("M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1")
            stroke("M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1")
        }
    }

    val Bolt: ImageVector by lazy {
        icon("Bolt") {
            stroke("M13 2 4 14h7l-1 8 9-12h-7z")
        }
    }

    val Search: ImageVector by lazy {
        icon("Search") {
            stroke("M4 11a7 7 0 1 0 14 0a7 7 0 1 0 -14 0z")
            stroke("m20 20-4-4")
        }
    }

    val Connections: ImageVector by lazy {
        icon("Connections") {
            stroke("M9.5 12a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0z")
            stroke("M3 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
            stroke("M17 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
            stroke("M3 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
            stroke("M17 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z")
            stroke("M7 7l3 3M17 7l-3 3M7 17l3-3M17 17l-3-3")
        }
    }

    val ArrowDown: ImageVector by lazy {
        icon("ArrowDown") {
            stroke("M12 5v14")
            stroke("m6 13 6 6 6-6")
        }
    }

    val ArrowUp: ImageVector by lazy {
        icon("ArrowUp") {
            stroke("M12 19V5")
            stroke("m6 11 6-6 6 6")
        }
    }

    val Lock: ImageVector by lazy {
        icon("Lock") {
            stroke("M7.5 11h9a2.5 2.5 0 0 1 2.5 2.5v4a2.5 2.5 0 0 1 -2.5 2.5h-9a2.5 2.5 0 0 1 -2.5 -2.5v-4a2.5 2.5 0 0 1 2.5 -2.5z")
            stroke("M8 11V8a4 4 0 0 1 8 0v3")
        }
    }

    val Sparkle: ImageVector by lazy {
        icon("Sparkle") {
            stroke("M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8z")
        }
    }

    val Block: ImageVector by lazy {
        icon("Block") {
            stroke("M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0z")
            stroke("m5.6 5.6 12.8 12.8")
        }
    }

    val List: ImageVector by lazy {
        icon("List") {
            stroke("M8 6h13M8 12h13M8 18h13M3 6h1M3 12h1M3 18h1")
        }
    }

    val ArrowForward: ImageVector by lazy {
        icon("ArrowForward") {
            stroke("M5 12h14")
            stroke("m13 6 6 6-6 6")
        }
    }

    val Gauge: ImageVector by lazy {
        icon("Gauge") {
            stroke("M4 18a8 8 0 1 1 16 0")
            stroke("m12 14 4-5")
        }
    }

    val Gift: ImageVector by lazy {
        icon("Gift") {
            stroke("M4 8h16a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1z")
            stroke("M5 13v8h14v-8M12 8v13")
            stroke("M12 8C10 4 7 4 7 6s3 2 5 2c2 0 5 0 5-2s-3-2-5 2z")
        }
    }

    val Tag: ImageVector by lazy {
        icon("Tag") {
            stroke("M3 12V4h8l10 10-8 8z")
            stroke("M6.2 8.5a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0z")
        }
    }

    val Close: ImageVector by lazy {
        icon("Close") {
            stroke("M6 6l12 12M18 6 6 18")
        }
    }

    val Pencil: ImageVector by lazy {
        icon("Pencil") {
            stroke("M4 20h4L19 9l-4-4L4 16z")
        }
    }

    val Card: ImageVector by lazy {
        icon("Card") {
            stroke("M6 5h12a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3z")
            stroke("M3 10h18M7 15h4")
        }
    }

    private class Paths(val builder: ImageVector.Builder) {
        fun stroke(data: String) {
            builder.addPath(
                pathData = addPathNodes(data),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }

        fun fill(data: String) {
            builder.addPath(pathData = addPathNodes(data), fill = SolidColor(Color.Black))
        }
    }

    private fun icon(name: String, block: Paths.() -> Unit): ImageVector {
        val builder = ImageVector.Builder(
            name = "Geek.$name",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        )
        Paths(builder).block()
        return builder.build()
    }
}
